In [4]:
from sklearn import tree
import pandas as pd
import os

In [6]:
df = pd.read_csv(os.path.join("Resources","temperature_and_ghg_concentrations_1880-2014_excluding_outliers.csv"))
df.head()

Year    GCAG  GISTEMP  Average Land Temperature (Degrees Celcius)  c-C4F8  \
0  1880 -0.1148    -0.20                                    8.118750     0.0   
1  1881 -0.0628    -0.12                                    8.270917     0.0   
2  1882 -0.0648    -0.10                                    8.128917     0.0   
3  1883 -0.1424    -0.21                                    7.976917     0.0   
4  1884 -0.2009    -0.28                                    7.773667     0.0   

       C2F6  C3F8  C4F10  C5F12  C6F14    ...     HFC245fa  HFC365mfc  \
0  0.000349   0.0    0.0    0.0    0.0    ...          0.0        0.0   
1  0.000363   0.0    0.0    0.0    0.0    ...          0.0        0.0   
2  0.000377   0.0    0.0    0.0    0.0    ...          0.0        0.0   
3  0.000392   0.0    0.0    0.0    0.0    ...          0.0        0.0   
4  0.000407   0.0    0.0    0.0    0.0    ...          0.0        0.0   

   HFC4310mee         CH4     CH3Br  CH3Cl  NF3         N20  SF6     SO2F2  
0         0.0  868.696106  5.299998  457.0  0.0  277.265047  0.0  0.000028  
1         0.0  870.984127  5.299998  457.0  0.0  277.374049  0.0  0.000029  
2         0.0  873.250134  5.299998  457.0  0.0  277.486048  0.0  0.000029  
3         0.0  875.603151  5.299998  457.0  0.0  277.591048  0.0  0.000029  
4         0.0  878.148195  5.299998  457.0  0.0  277.695048  0.0  0.000029  

[5 rows x 46 columns]

In [7]:
target = df["GCAG"]

In [8]:
clean_data = df.drop(["Average Land Temperature (Degrees Celcius)", "GISTEMP", "GCAG", "Year"], axis=1)
feature_names = clean_data.columns
clean_data.head()

c-C4F8      C2F6  C3F8  C4F10  C5F12  C6F14  C7F16  C8F18         CO2  \
0     0.0  0.000349   0.0    0.0    0.0    0.0    0.0    0.0  289.469999   
1     0.0  0.000363   0.0    0.0    0.0    0.0    0.0    0.0  289.736999   
2     0.0  0.000377   0.0    0.0    0.0    0.0    0.0    0.0  290.018999   
3     0.0  0.000392   0.0    0.0    0.0    0.0    0.0    0.0  290.262999   
4     0.0  0.000407   0.0    0.0    0.0    0.0    0.0    0.0  290.511999   

    CCl4    ...     HFC245fa  HFC365mfc  HFC4310mee         CH4     CH3Br  \
0  0.025    ...          0.0        0.0         0.0  868.696106  5.299998   
1  0.025    ...          0.0        0.0         0.0  870.984127  5.299998   
2  0.025    ...          0.0        0.0         0.0  873.250134  5.299998   
3  0.025    ...          0.0        0.0         0.0  875.603151  5.299998   
4  0.025    ...          0.0        0.0         0.0  878.148195  5.299998   

   CH3Cl  NF3         N20  SF6     SO2F2  
0  457.0  0.0  277.265047  0.0  0.000028  
1  457.0  0.0  277.374049  0.0  0.000029  
2  457.0  0.0  277.486048  0.0  0.000029  
3  457.0  0.0  277.591048  0.0  0.000029  
4  457.0  0.0  277.695048  0.0  0.000029  

[5 rows x 42 columns]

In [9]:
# Convert to numpy arrays
import numpy as np

features = np.array(clean_data)
target_final = np.array(target)

# Training and Testing Sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target_final, random_state = 42)

In [10]:
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8144340107762558

In [11]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=5000)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8897488969528657

In [12]:
results = sorted(zip(rf.feature_importances_, feature_names), reverse=True)

In [13]:
new_df = pd.DataFrame(results)

In [14]:
new_df.to_csv('resultsGCAG_excluding_outliers.csv', index=False) 

In [15]:
results

[(0.07645909728048247, 'HFC23'),
 (0.05403611954101968, 'HFC236fa'),
 (0.04374778939949115, 'CH2Cl2'),
 (0.04267783666609314, 'HCFC22'),
 (0.04072509362215295, 'CO2'),
 (0.037816364491821096, 'CF4'),
 (0.03668453012709364, 'N20'),
 (0.03637365172212002, 'HFC32'),
 (0.03613658384594316, 'SO2F2'),
 (0.03347832074080164, 'CH4'),
 (0.033163042934130735, 'C2F6'),
 (0.032733257099322705, 'C3F8'),
 (0.03216748765760225, 'HFC227ea'),
 (0.03194870362565666, 'CFC113'),
 (0.03082298606212566, 'Halon2402'),
 (0.026274218932399424, 'CFC114'),
 (0.026011759172342965, 'CFC115'),
 (0.024882411642090794, 'NF3'),
 (0.02155022661988611, 'CCl4'),
 (0.021424145097577316, 'CHCl3'),
 (0.020163478214562054, 'CFC11'),
 (0.019836488446400808, 'HFC152a'),
 (0.019352562908030144, 'CH3Br'),
 (0.01875014662482264, 'HCFC142b'),
 (0.018561222573678867, 'c-C4F8'),
 (0.017808390569320643, 'HFC143a'),
 (0.017360331410202108, 'CFC12'),
 (0.01705213889481135, 'C7F16'),
 (0.016822468979282128, 'C6F14'),
 (0.016666924312233

In [18]:
df2 = pd.read_csv("Trended_MoleculeConcentration_excludingoutliers.csv")
df2 = df2.set_index("Unnamed: 0")

In [19]:
x1950_1970 = df2.iloc[0].values.reshape(1, -1)
x1970_1988 = df2.iloc[1].values.reshape(1, -1)
x1988_2014 = df2.iloc[2].values.reshape(1, -1)
x2009_2014 = df2.iloc[3].values.reshape(1, -1)

In [20]:
 rf.predict(x1950_1970)

array([0.18394795])

In [21]:
rf.predict(x1970_1988)

array([0.46712567])

In [22]:
rf.predict(x1988_2014)

array([0.69029397])

In [23]:
rf.predict(x2009_2014)

array([0.65722144])