In [44]:
from sklearn import tree
import pandas as pd
import os

In [4]:
df = pd.read_csv(os.path.join("Resources", "testing.csv"))
df.head()

Year    GCAG  GISTEMP  Average Land Temperature (Degrees Celcius)  c-C4F8  \
0  1880 -0.1148    -0.20                                    8.118750     0.0   
1  1881 -0.0628    -0.12                                    8.270917     0.0   
2  1882 -0.0648    -0.10                                    8.128917     0.0   
3  1883 -0.1424    -0.21                                    7.976917     0.0   
4  1884 -0.2009    -0.28                                    7.773667     0.0   

       C2F6  C3F8  C4F10  C5F12  C6F14    ...     HFC245fa  HFC365mfc  \
0  0.000349   0.0    0.0    0.0    0.0    ...          0.0        0.0   
1  0.000363   0.0    0.0    0.0    0.0    ...          0.0        0.0   
2  0.000377   0.0    0.0    0.0    0.0    ...          0.0        0.0   
3  0.000392   0.0    0.0    0.0    0.0    ...          0.0        0.0   
4  0.000407   0.0    0.0    0.0    0.0    ...          0.0        0.0   

   HFC4310mee         CH4     CH3Br  CH3Cl  NF3         N20  SF6     SO2F2  
0         0.0  868.696106  5.299998  457.0  0.0  277.265047  0.0  0.000028  
1         0.0  870.984127  5.299998  457.0  0.0  277.374049  0.0  0.000029  
2         0.0  873.250134  5.299998  457.0  0.0  277.486048  0.0  0.000029  
3         0.0  875.603151  5.299998  457.0  0.0  277.591048  0.0  0.000029  
4         0.0  878.148195  5.299998  457.0  0.0  277.695048  0.0  0.000029  

[5 rows x 47 columns]

In [5]:
target = df["GCAG"]

In [6]:
clean_data = df.drop(["Average Land Temperature (Degrees Celcius)", "GISTEMP", "GCAG", "Year"], axis=1)
feature_names = clean_data.columns
clean_data.head()

c-C4F8      C2F6  C3F8  C4F10  C5F12  C6F14  C7F16  C8F18         CO2  \
0     0.0  0.000349   0.0    0.0    0.0    0.0    0.0    0.0  289.469999   
1     0.0  0.000363   0.0    0.0    0.0    0.0    0.0    0.0  289.736999   
2     0.0  0.000377   0.0    0.0    0.0    0.0    0.0    0.0  290.018999   
3     0.0  0.000392   0.0    0.0    0.0    0.0    0.0    0.0  290.262999   
4     0.0  0.000407   0.0    0.0    0.0    0.0    0.0    0.0  290.511999   

    CCl4    ...     HFC245fa  HFC365mfc  HFC4310mee         CH4     CH3Br  \
0  0.025    ...          0.0        0.0         0.0  868.696106  5.299998   
1  0.025    ...          0.0        0.0         0.0  870.984127  5.299998   
2  0.025    ...          0.0        0.0         0.0  873.250134  5.299998   
3  0.025    ...          0.0        0.0         0.0  875.603151  5.299998   
4  0.025    ...          0.0        0.0         0.0  878.148195  5.299998   

   CH3Cl  NF3         N20  SF6     SO2F2  
0  457.0  0.0  277.265047  0.0  0.000028  
1  457.0  0.0  277.374049  0.0  0.000029  
2  457.0  0.0  277.486048  0.0  0.000029  
3  457.0  0.0  277.591048  0.0  0.000029  
4  457.0  0.0  277.695048  0.0  0.000029  

[5 rows x 43 columns]

In [7]:
# Convert to numpy arrays
import numpy as np

features = np.array(clean_data)
target_final = np.array(target)

# Training and Testing Sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target_final, random_state = 42)

In [8]:
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8070142381252726

In [9]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=5000)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8943353591118544

In [10]:
results = sorted(zip(rf.feature_importances_, feature_names), reverse=True)

In [11]:
new_df = pd.DataFrame(results)

In [12]:
new_df.to_csv('resultsGCAG.csv', index=False) 

In [13]:
results

[(0.12947082961665493, 'Halon1211'),
 (0.06486327807593809, 'HFC23'),
 (0.03921408252152033, 'HCFC22'),
 (0.0360255075273693, 'HFC236fa'),
 (0.035048122186610325, 'CO2'),
 (0.03367592873965089, 'CH2Cl2'),
 (0.03331039786048332, 'CH4'),
 (0.032732368898138874, 'SO2F2'),
 (0.03266585301045957, 'HFC227ea'),
 (0.03125902969532556, 'CFC113'),
 (0.030552333197161472, 'C2F6'),
 (0.0305476938933994, 'HFC32'),
 (0.03006562704149266, 'C3F8'),
 (0.029502467701480014, 'CF4'),
 (0.029210270284285616, 'N20'),
 (0.025570786025809426, 'Halon2402'),
 (0.023543438455429437, 'NF3'),
 (0.021306211345154518, 'CFC114'),
 (0.021189960801415084, 'CFC115'),
 (0.020649800849308477, 'CHCl3'),
 (0.01926267709188756, 'CCl4'),
 (0.018978390366646624, 'CH3Br'),
 (0.018039020878845263, 'HFC152a'),
 (0.01728294191108423, 'CFC11'),
 (0.016852841670158807, 'HCFC142b'),
 (0.01636187952650774, 'CFC12'),
 (0.01592588532837486, 'HFC365mfc'),
 (0.015094442160996797, 'c-C4F8'),
 (0.014329133784884502, 'C8F18'),
 (0.0141960411

In [37]:
df2 = pd.read_csv("Trended_MoleculeConcentration.csv")

In [38]:
df2 = df2.set_index("Unnamed: 0")


In [39]:
x1950_1970 = df2.iloc[0].values.reshape(1, -1)
x1970_1988 = df2.iloc[1].values.reshape(1, -1)
x1988_2014 = df2.iloc[2].values.reshape(1, -1)
x2009_2014 = df2.iloc[3].values.reshape(1, -1)

In [40]:
 rf.predict(x1950_1970)

array([0.14573442])

In [41]:
rf.predict(x1970_1988)

array([0.46934288])

In [42]:
rf.predict(x1988_2014)

array([0.68908108])

In [43]:
rf.predict(x2009_2014)

array([0.6534004])