In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
df = pd.read_csv(os.path.join("Resources", "testing.csv"))
df.head()

Year    GCAG  GISTEMP  Average Land Temperature (Degrees Celcius)  c-C4F8  \
0  1880 -0.1148    -0.20                                    8.118750     0.0   
1  1881 -0.0628    -0.12                                    8.270917     0.0   
2  1882 -0.0648    -0.10                                    8.128917     0.0   
3  1883 -0.1424    -0.21                                    7.976917     0.0   
4  1884 -0.2009    -0.28                                    7.773667     0.0   

       C2F6  C3F8  C4F10  C5F12  C6F14    ...     HFC245fa  HFC365mfc  \
0  0.000349   0.0    0.0    0.0    0.0    ...          0.0        0.0   
1  0.000363   0.0    0.0    0.0    0.0    ...          0.0        0.0   
2  0.000377   0.0    0.0    0.0    0.0    ...          0.0        0.0   
3  0.000392   0.0    0.0    0.0    0.0    ...          0.0        0.0   
4  0.000407   0.0    0.0    0.0    0.0    ...          0.0        0.0   

   HFC4310mee         CH4     CH3Br  CH3Cl  NF3         N20  SF6     SO2F2  
0         0.0  868.696106  5.299998  457.0  0.0  277.265047  0.0  0.000028  
1         0.0  870.984127  5.299998  457.0  0.0  277.374049  0.0  0.000029  
2         0.0  873.250134  5.299998  457.0  0.0  277.486048  0.0  0.000029  
3         0.0  875.603151  5.299998  457.0  0.0  277.591048  0.0  0.000029  
4         0.0  878.148195  5.299998  457.0  0.0  277.695048  0.0  0.000029  

[5 rows x 47 columns]

In [3]:
target = df["GISTEMP"]

In [4]:
clean_data = df.drop(["Average Land Temperature (Degrees Celcius)", "GISTEMP", "GCAG", "Year"], axis=1)
feature_names = clean_data.columns
clean_data.head()

c-C4F8      C2F6  C3F8  C4F10  C5F12  C6F14  C7F16  C8F18         CO2  \
0     0.0  0.000349   0.0    0.0    0.0    0.0    0.0    0.0  289.469999   
1     0.0  0.000363   0.0    0.0    0.0    0.0    0.0    0.0  289.736999   
2     0.0  0.000377   0.0    0.0    0.0    0.0    0.0    0.0  290.018999   
3     0.0  0.000392   0.0    0.0    0.0    0.0    0.0    0.0  290.262999   
4     0.0  0.000407   0.0    0.0    0.0    0.0    0.0    0.0  290.511999   

    CCl4    ...     HFC245fa  HFC365mfc  HFC4310mee         CH4     CH3Br  \
0  0.025    ...          0.0        0.0         0.0  868.696106  5.299998   
1  0.025    ...          0.0        0.0         0.0  870.984127  5.299998   
2  0.025    ...          0.0        0.0         0.0  873.250134  5.299998   
3  0.025    ...          0.0        0.0         0.0  875.603151  5.299998   
4  0.025    ...          0.0        0.0         0.0  878.148195  5.299998   

   CH3Cl  NF3         N20  SF6     SO2F2  
0  457.0  0.0  277.265047  0.0  0.000028  
1  457.0  0.0  277.374049  0.0  0.000029  
2  457.0  0.0  277.486048  0.0  0.000029  
3  457.0  0.0  277.591048  0.0  0.000029  
4  457.0  0.0  277.695048  0.0  0.000029  

[5 rows x 43 columns]

In [5]:
# Convert to numpy arrays
import numpy as np

features = np.array(clean_data)
target_final = np.array(target)

# Training and Testing Sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target_final, random_state = 42)

In [6]:
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.7961483300707476

In [7]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8953818154834283

In [19]:
rf2 = rf.fit(features, target_final)

In [20]:
import graphviz 

dot_data = tree.export_graphviz(
    rf2, out_file=None, 
    feature_names=features,  
    class_names=target_final,  
    filled=True, rounded=True,  
    special_characters=False)  

import pydotplus
graph = pydotplus.graph_from_dot_data(dot_data)

graph = graphviz.Source(dot_data)  
graph 

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [8]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.12471343172873954, 'Halon1211'),
 (0.08041375154106677, 'HFC227ea'),
 (0.050879092338370714, 'HFC365mfc'),
 (0.04717358083275015, 'Halon2402'),
 (0.038710256083495, 'HFC23'),
 (0.03823998636063352, 'SO2F2'),
 (0.036705111267003335, 'CFC113'),
 (0.03642156184507412, 'CFC11'),
 (0.03097202043556183, 'HFC143a'),
 (0.02946535596958847, 'CF4'),
 (0.027091040887124503, 'HFC152a'),
 (0.027083340342138842, 'CH2Cl2'),
 (0.026394963413092554, 'N20'),
 (0.024388935600391633, 'CH4'),
 (0.023336039735024926, 'CHCl3'),
 (0.022650893170445944, 'C5F12'),
 (0.022649739579739658, 'HFC32'),
 (0.022397886399447165, 'CCl4'),
 (0.02083568522769183, 'HFC236fa'),
 (0.020810734184970526, 'CH3Br'),
 (0.020731704831327996, 'CO2'),
 (0.01929527214984749, 'Halon1301'),
 (0.019176960130445828, 'C3F8'),
 (0.018615467391231107, 'HCFC22'),
 (0.016711429512981255, 'CFC12'),
 (0.016279448138093802, 'C2F6'),
 (0.01579790087041816, 'NF3'),
 (0.015681562499837213, 'C6F14'),
 (0.015655039402359325, 'CFC115'),
 (0.013083

In [9]:
df2 = pd.read_csv("Trended_MoleculeConcentration.csv")
df2 = df2.set_index("Unnamed: 0")
x1950_1970 = df2.iloc[0].values.reshape(1, -1)
x1970_1988 = df2.iloc[1].values.reshape(1, -1)
x1988_2014 = df2.iloc[2].values.reshape(1, -1)
x2009_2014 = df2.iloc[3].values.reshape(1, -1)

In [10]:
 rf.predict(x1950_1970)

array([0.0627])

In [11]:
rf.predict(x1970_1988)

array([0.46315])

In [12]:
rf.predict(x1988_2014)

array([0.689])

In [13]:
rf.predict(x2009_2014)

array([0.6526])