In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
df = pd.read_csv(os.path.join("Resources", "testing.csv"))
df.head()

Year    GCAG  GISTEMP  Average Land Temperature (Degrees Celcius)  c-C4F8  \
0  1880 -0.1148    -0.20                                    8.118750     0.0   
1  1881 -0.0628    -0.12                                    8.270917     0.0   
2  1882 -0.0648    -0.10                                    8.128917     0.0   
3  1883 -0.1424    -0.21                                    7.976917     0.0   
4  1884 -0.2009    -0.28                                    7.773667     0.0   

       C2F6  C3F8  C4F10  C5F12  C6F14    ...     HFC245fa  HFC365mfc  \
0  0.000349   0.0    0.0    0.0    0.0    ...          0.0        0.0   
1  0.000363   0.0    0.0    0.0    0.0    ...          0.0        0.0   
2  0.000377   0.0    0.0    0.0    0.0    ...          0.0        0.0   
3  0.000392   0.0    0.0    0.0    0.0    ...          0.0        0.0   
4  0.000407   0.0    0.0    0.0    0.0    ...          0.0        0.0   

   HFC4310mee         CH4     CH3Br  CH3Cl  NF3         N20  SF6     SO2F2  
0         0.0  868.696106  5.299998  457.0  0.0  277.265047  0.0  0.000028  
1         0.0  870.984127  5.299998  457.0  0.0  277.374049  0.0  0.000029  
2         0.0  873.250134  5.299998  457.0  0.0  277.486048  0.0  0.000029  
3         0.0  875.603151  5.299998  457.0  0.0  277.591048  0.0  0.000029  
4         0.0  878.148195  5.299998  457.0  0.0  277.695048  0.0  0.000029  

[5 rows x 47 columns]

In [3]:
target = df["GISTEMP"]

In [4]:
clean_data = df.drop(["Average Land Temperature (Degrees Celcius)", "GISTEMP", "GCAG", "Year"], axis=1)
feature_names = clean_data.columns
clean_data.head()

c-C4F8      C2F6  C3F8  C4F10  C5F12  C6F14  C7F16  C8F18         CO2  \
0     0.0  0.000349   0.0    0.0    0.0    0.0    0.0    0.0  289.469999   
1     0.0  0.000363   0.0    0.0    0.0    0.0    0.0    0.0  289.736999   
2     0.0  0.000377   0.0    0.0    0.0    0.0    0.0    0.0  290.018999   
3     0.0  0.000392   0.0    0.0    0.0    0.0    0.0    0.0  290.262999   
4     0.0  0.000407   0.0    0.0    0.0    0.0    0.0    0.0  290.511999   

    CCl4    ...     HFC245fa  HFC365mfc  HFC4310mee         CH4     CH3Br  \
0  0.025    ...          0.0        0.0         0.0  868.696106  5.299998   
1  0.025    ...          0.0        0.0         0.0  870.984127  5.299998   
2  0.025    ...          0.0        0.0         0.0  873.250134  5.299998   
3  0.025    ...          0.0        0.0         0.0  875.603151  5.299998   
4  0.025    ...          0.0        0.0         0.0  878.148195  5.299998   

   CH3Cl  NF3         N20  SF6     SO2F2  
0  457.0  0.0  277.265047  0.0  0.000028  
1  457.0  0.0  277.374049  0.0  0.000029  
2  457.0  0.0  277.486048  0.0  0.000029  
3  457.0  0.0  277.591048  0.0  0.000029  
4  457.0  0.0  277.695048  0.0  0.000029  

[5 rows x 43 columns]

In [5]:
# Convert to numpy arrays
import numpy as np

features = np.array(clean_data)
target_final = np.array(target)

# Training and Testing Sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target_final, random_state = 42)

In [6]:
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8362961682107313

In [7]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8963584831703273

In [8]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.11289546586359407, 'Halon1211'),
 (0.10234984144515058, 'HFC227ea'),
 (0.04332107824779291, 'Halon2402'),
 (0.041288284120924584, 'C2F6'),
 (0.03884773935333022, 'HFC365mfc'),
 (0.03821438081604804, 'HFC23'),
 (0.03792776622623254, 'N20'),
 (0.03574994659406967, 'HCFC22'),
 (0.03405812510073135, 'CO2'),
 (0.02888147496428263, 'CH2Cl2'),
 (0.028348954403425174, 'SO2F2'),
 (0.027234615736752243, 'C6F14'),
 (0.02504201832067349, 'C3F8'),
 (0.02480422928408527, 'NF3'),
 (0.02419707293634815, 'CHCl3'),
 (0.02311144270416448, 'CFC12'),
 (0.022554777388499522, 'CH4'),
 (0.022458413004808126, 'HFC32'),
 (0.02089701165018429, 'C7F16'),
 (0.020394483675868814, 'CFC113'),
 (0.019706572182961953, 'HFC236fa'),
 (0.019265365144600824, 'CCl4'),
 (0.01876298283047339, 'CF4'),
 (0.017071669434466342, 'CFC114'),
 (0.0164572045812904, 'CH3Br'),
 (0.016104652034964206, 'CFC115'),
 (0.015816406556145846, 'C5F12'),
 (0.015626447807706972, 'SF6'),
 (0.015310583980099815, 'c-C4F8'),
 (0.012998292860995915

In [9]:
df2 = pd.read_csv("Trended_MoleculeConcentration.csv")
df2 = df2.set_index("Unnamed: 0")
x1950_1970 = df2.iloc[0].values.reshape(1, -1)
x1970_1988 = df2.iloc[1].values.reshape(1, -1)
x1988_2014 = df2.iloc[2].values.reshape(1, -1)
x2009_2014 = df2.iloc[3].values.reshape(1, -1)

In [10]:
 rf.predict(x1950_1970)

array([0.0889])

In [11]:
rf.predict(x1970_1988)

array([0.4525])

In [12]:
rf.predict(x1988_2014)

array([0.68005])

In [13]:
rf.predict(x2009_2014)

array([0.6603])